/**
 * TEMPORARY DIAGNOSTIC — GET /api/cron/diag-duplicate-signals
 *
 * Real check for Step 2 of the duplicate-active-signals audit: any ticker
 * with more than one isActive:true row, in Signal and OptionsSignal
 * separately (equity and options are different instrument types by
 * definition — different tables here, never compared against each other).
 * Report-only. Delete after use.
 */
import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'
export const maxDuration = 30

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    const dupSignalTickers = await prisma.$queryRaw<{ ticker: string; count: bigint }[]>`
      SELECT ticker, COUNT(*) as count FROM "Signal"
      WHERE "isActive" = true
      GROUP BY ticker HAVING COUNT(*) > 1
      ORDER BY count DESC
    `
    const dupOptionsTickers = await prisma.$queryRaw<{ ticker: string; count: bigint }[]>`
      SELECT ticker, COUNT(*) as count FROM "OptionsSignal"
      WHERE "isActive" = true
      GROUP BY ticker HAVING COUNT(*) > 1
      ORDER BY count DESC
    `

    const signalDetails = dupSignalTickers.length > 0
      ? await prisma.signal.findMany({
          where: { ticker: { in: dupSignalTickers.map((d) => d.ticker) }, isActive: true },
          select: {
            id: true, ticker: true, signalType: true, confidence: true, timeframeCategory: true,
            session: true, isManual: true, autoGenerated: true, createdAt: true, signalDate: true,
            entryZoneLow: true, entryZoneHigh: true, targetPrice: true, stopLoss: true, thesis: true,
          },
          orderBy: [{ ticker: 'asc' }, { createdAt: 'asc' }],
        })
      : []

    const optionsDetails = dupOptionsTickers.length > 0
      ? await prisma.optionsSignal.findMany({
          where: { ticker: { in: dupOptionsTickers.map((d) => d.ticker) }, isActive: true },
          select: {
            id: true, ticker: true, contractType: true, strikePrice: true, expirationDate: true,
            confidence: true, isManual: true, autoGenerated: true, createdAt: true,
          },
          orderBy: [{ ticker: 'asc' }, { createdAt: 'asc' }],
        })
      : []

    return NextResponse.json({
      ok: true,
      duplicateSignalTickerCount: dupSignalTickers.length,
      duplicateSignalTickers: dupSignalTickers.map((d) => ({ ticker: d.ticker, count: Number(d.count) })),
      signalDetails,
      duplicateOptionsTickerCount: dupOptionsTickers.length,
      duplicateOptionsTickers: dupOptionsTickers.map((d) => ({ ticker: d.ticker, count: Number(d.count) })),
      optionsDetails,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: 'Internal error', message: msg }, { status: 500 })
  }
}
