import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function GET() {
  const results: Record<string, unknown> = {}

  try {
    const signals = await prisma.signal.findMany({ where: { isActive: true }, orderBy: { signalDate: 'desc' } })
    results.signals = { count: signals.length, sample: signals.slice(0, 2).map(s => ({ ticker: s.ticker, type: s.signalType, autoGenerated: s.autoGenerated, signalDate: s.signalDate, entryLow: s.entryZoneLow, entryHigh: s.entryZoneHigh, target: s.targetPrice, stop: s.stopLoss, aiSummaryLen: s.aiSummary?.length ?? 0, thesisLen: s.thesis?.length ?? 0 })) }
  } catch (e) {
    results.signals = { error: String(e) }
  }

  try {
    const log = await prisma.signalGenerationLog.findFirst({ where: { status: 'success' }, orderBy: { generatedAt: 'desc' } })
    results.lastLog = log ? { generatedAt: log.generatedAt, count: log.signalCount } : null
  } catch (e) {
    results.lastLog = { error: String(e) }
  }

  try {
    await prisma.user.count()
    results.userTable = 'ok'
  } catch (e) {
    results.userTable = { error: String(e) }
  }

  try {
    await prisma.newsArticle.count()
    results.newsTable = 'ok'
  } catch (e) {
    results.newsTable = { error: String(e) }
  }

  return NextResponse.json(results)
}
