/**
 * GET /api/diag
 *
 * Internal diagnostics endpoint — ADMIN ONLY.
 *
 * Security: Requires ADMIN_USER_ID authentication. Previously this route had
 * no auth and leaked database row counts and signal samples to anyone.
 */

import { NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { prisma } from '@/lib/prisma'
import {
  checkRateLimit,
  tooManyRequests,
  ADMIN_LIMIT,
  ADMIN_WINDOW_MS,
} from '@/lib/rate-limit'

export async function GET() {
  // ── Auth: admin only ────────────────────────────────────────────────────────
  const { userId } = await auth()
  if (!userId || userId !== process.env.ADMIN_USER_ID) {
    // Return 404 rather than 403 to avoid revealing that this endpoint exists.
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  // ── Rate limiting ───────────────────────────────────────────────────────────
  const rl = checkRateLimit(`diag:${userId}`, ADMIN_LIMIT, ADMIN_WINDOW_MS)
  if (!rl.success) return tooManyRequests(rl.retryAfter!)

  const results: Record<string, unknown> = {}

  try {
    const signals = await prisma.signal.findMany({
      where: { isActive: true },
      orderBy: { signalDate: 'desc' },
    })
    results.signals = {
      count: signals.length,
      sample: signals.slice(0, 2).map(s => ({
        ticker:        s.ticker,
        type:          s.signalType,
        autoGenerated: s.autoGenerated,
        signalDate:    s.signalDate,
        entryLow:      s.entryZoneLow,
        entryHigh:     s.entryZoneHigh,
        target:        s.targetPrice,
        stop:          s.stopLoss,
        aiSummaryLen:  s.aiSummary?.length ?? 0,
        thesisLen:     s.thesis?.length ?? 0,
      })),
    }
  } catch {
    results.signals = { error: 'Query failed' }
  }

  try {
    const log = await prisma.signalGenerationLog.findFirst({
      where: { status: 'success' },
      orderBy: { generatedAt: 'desc' },
    })
    results.lastLog = log ? { generatedAt: log.generatedAt, count: log.signalCount } : null
  } catch {
    results.lastLog = { error: 'Query failed' }
  }

  try {
    await prisma.user.count()
    results.userTable = 'ok'
  } catch {
    results.userTable = { error: 'Query failed' }
  }

  try {
    await prisma.newsArticle.count()
    results.newsTable = 'ok'
  } catch {
    results.newsTable = { error: 'Query failed' }
  }

  return NextResponse.json(results)
}
