import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getAnthropicClient } from '@/lib/anthropic'

export const maxDuration = 60

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return process.env.NODE_ENV !== 'production'
  return req.headers.get('authorization') === `Bearer ${secret}`
}

const WATCHLIST = [
  'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META', 'AMZN', 'TSLA', 'AMD', 'AVGO', 'QCOM',
  'JPM', 'BAC', 'GS', 'V', 'MA', 'JNJ', 'UNH', 'LLY', 'PFE', 'XOM',
  'CVX', 'WMT', 'MCD', 'NFLX', 'CRM', 'PLTR', 'COIN', 'UBER', 'CAT', 'BA',
]

type Quote = { c: number; d: number; dp: number; h: number; l: number; o: number; pc: number; t: number }
type NewsItem = { headline: string; datetime: number; source: string }

async function fetchQuote(symbol: string): Promise<Quote | null> {
  const key = process.env.FINNHUB_API_KEY
  if (!key) return null
  try {
    const res = await fetch(`https://finnhub.io/api/v1/quote?symbol=${symbol}&token=${key}`, { cache: 'no-store' })
    if (!res.ok) return null
    return res.json()
  } catch { return null }
}

async function fetchRecentNews(symbol: string): Promise<NewsItem[]> {
  const key = process.env.FINNHUB_API_KEY
  if (!key) return []
  const to = new Date().toISOString().split('T')[0]
  const from = new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0]
  try {
    const res = await fetch(`https://finnhub.io/api/v1/company-news?symbol=${symbol}&from=${from}&to=${to}&token=${key}`, { cache: 'no-store' })
    if (!res.ok) return []
    const data: NewsItem[] = await res.json()
    return data.slice(0, 3)
  } catch { return [] }
}

type StockData = {
  symbol: string
  price: number
  change: number
  changePct: number
  high52w: number
  low52w: number
  recentHeadlines: string[]
}

type GeneratedSignal = {
  ticker: string
  companyName: string
  signalType: 'BUY' | 'WATCH' | 'SHORT'
  entryZoneLow: number
  entryZoneHigh: number
  targetPrice: number
  stopLoss: number
  confidence: number
  timeHorizon: string
  thesis: string
  aiSummary: string
  sector: string
}

async function generateSignals(stocks: StockData[]): Promise<GeneratedSignal[]> {
  const client = getAnthropicClient()

  const stocksJson = stocks.map((s) => ({
    symbol: s.symbol,
    price: s.price,
    changePct: s.changePct,
    high52w: s.high52w,
    low52w: s.low52w,
    recentHeadlines: s.recentHeadlines,
  }))

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    messages: [
      {
        role: 'user',
        content: `You are a professional equity analyst. Analyze these stocks and generate trading signals for the most actionable ones (select 8-12). Reply with a JSON array only, no markdown, no explanation.

For each signal include:
- ticker (string)
- companyName (string, full company name)
- signalType ("BUY", "WATCH", or "SHORT")
- entryZoneLow (number, realistic price)
- entryZoneHigh (number, realistic price)
- targetPrice (number)
- stopLoss (number)
- confidence (integer 0-100)
- timeHorizon (string, e.g. "2-4 weeks", "1-3 months")
- thesis (string, 1-2 sentences on why)
- aiSummary (string, 1 sentence summary)
- sector (string, e.g. "Technology", "Healthcare", "Finance", "Energy", "Consumer", "Industrials")

Stock data:
${JSON.stringify(stocksJson, null, 2)}`,
      },
    ],
  })

  const text = message.content[0].type === 'text' ? message.content[0].text : '[]'
  try {
    return JSON.parse(text) as GeneratedSignal[]
  } catch {
    return []
  }
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    const stockData = await Promise.all(
      WATCHLIST.map(async (symbol) => {
        const [quote, news] = await Promise.all([fetchQuote(symbol), fetchRecentNews(symbol)])
        return {
          symbol,
          price: quote?.c ?? 0,
          change: quote?.d ?? 0,
          changePct: quote?.dp ?? 0,
          high52w: quote?.h ?? 0,
          low52w: quote?.l ?? 0,
          recentHeadlines: news.map((n) => n.headline),
        } satisfies StockData
      })
    )

    const withData = stockData.filter((s) => s.price > 0)
    if (withData.length === 0) {
      await prisma.signalGenerationLog.create({ data: { signalCount: 0, status: 'no_data' } })
      return NextResponse.json({ ok: true, count: 0 })
    }

    const signals = await generateSignals(withData)
    if (signals.length === 0) {
      await prisma.signalGenerationLog.create({ data: { signalCount: 0, status: 'no_signals' } })
      return NextResponse.json({ ok: true, count: 0 })
    }

    await prisma.$transaction([
      prisma.signal.updateMany({ where: { autoGenerated: true }, data: { isActive: false } }),
      ...signals.map((s) =>
        prisma.signal.create({
          data: {
            ticker: s.ticker,
            companyName: s.companyName,
            signalType: s.signalType,
            entryZoneLow: s.entryZoneLow,
            entryZoneHigh: s.entryZoneHigh,
            targetPrice: s.targetPrice,
            stopLoss: s.stopLoss,
            confidence: s.confidence,
            timeHorizon: s.timeHorizon,
            thesis: s.thesis,
            aiSummary: s.aiSummary,
            sector: s.sector,
            isActive: true,
            autoGenerated: true,
          },
        })
      ),
      prisma.signalGenerationLog.create({ data: { signalCount: signals.length, status: 'success' } }),
    ])

    return NextResponse.json({ ok: true, count: signals.length })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error('[cron/signals]', msg)
    await prisma.signalGenerationLog.create({ data: { signalCount: 0, status: 'error', error: msg } }).catch(() => {})
    return NextResponse.json({ error: 'Internal error' }, { status: 500 })
  }
}
