import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const low = await prisma.signal.findMany({
    where: { isActive: true, confidence: { lt: 55 } },
    select: { id: true, ticker: true, confidence: true, autoGenerated: true, createdAt: true },
    orderBy: { confidence: 'asc' },
  })
  const totalActive = await prisma.signal.count({ where: { isActive: true } })
  return NextResponse.json({ totalActive, belowFloorCount: low.length, belowFloor: low })
}
