import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const active = await prisma.signal.findMany({
    where: { isActive: true },
    select: {
      ticker: true,
      signalCategory: true,
      timeHorizon: true,
      autoGenerated: true,
      createdAt: true,
      signalDate: true,
    },
    orderBy: { createdAt: 'desc' },
  })

  const byCategory: Record<string, number> = {}
  const byTimeHorizon: Record<string, number> = {}
  for (const s of active) {
    byCategory[s.signalCategory] = (byCategory[s.signalCategory] ?? 0) + 1
    byTimeHorizon[s.timeHorizon] = (byTimeHorizon[s.timeHorizon] ?? 0) + 1
  }

  const recentLogs = await prisma.signalGenerationLog.findMany({
    orderBy: { generatedAt: 'desc' },
    take: 10,
  })

  return NextResponse.json({
    totalActive: active.length,
    byCategory,
    byTimeHorizon,
    recentLogs,
    sample: active.slice(0, 10),
  })
}
