import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getAnthropicClient } from '@/lib/anthropic'

export const maxDuration = 60

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

// High-volume tickers well-suited for options analysis
const OPTIONS_TICKERS = [
  'AAPL', 'MSFT', 'NVDA', 'TSLA', 'META', 'AMZN', 'GOOGL', 'AMD', 'SPY', 'QQQ',
  'PLTR', 'COIN', 'NFLX', 'UBER', 'CRM', 'AVGO', 'V', 'JPM', 'BAC', 'XOM',
]

type Quote = { c: number; dp: number; h: number; l: number }

async function fetchQuote(symbol: string): Promise<Quote | null> {
  const key = process.env.FINNHUB_API_KEY
  if (!key) return null
  try {
    const res = await fetch(`https://finnhub.io/api/v1/quote?symbol=${symbol}&token=${key}`, { cache: 'no-store' })
    if (!res.ok) return null
    return res.json()
  } catch { return null }
}

type GeneratedOption = {
  ticker: string
  companyName: string
  contractType: 'CALL' | 'PUT'
  strikePrice: number
  expirationDate: string
  premiumEstimate: number
  confidence: number
  reasoning: string
  summary: string
  riskLevel: 'High' | 'Medium' | 'Low'
}

async function generateOptionsSignals(
  stocks: { symbol: string; price: number; changePct: number; high52w: number; low52w: number }[]
): Promise<GeneratedOption[]> {
  const client = getAnthropicClient()

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    messages: [
      {
        role: 'user',
        content: `You are an expert options trader. Based on the stock data below, generate 6-10 actionable options trades. Choose CALL or PUT based on your directional conviction. Set realistic strike prices near current price, expiration 2-6 weeks out, and estimate a reasonable premium range. Reply with a JSON array only, no markdown.

Each item must include:
- ticker (string)
- companyName (string, full name)
- contractType ("CALL" or "PUT")
- strikePrice (number, near current price)
- expirationDate (string, "YYYY-MM-DD", 2-6 weeks from today)
- premiumEstimate (number, realistic USD per contract, e.g. 2.50)
- confidence (integer 0-100)
- reasoning (string, 2-3 sentences on why this trade makes sense)
- summary (string, 1 sentence)
- riskLevel ("High", "Medium", or "Low")

Today: ${new Date().toISOString().split('T')[0]}

Stock data:
${JSON.stringify(stocks, null, 2)}`,
      },
    ],
  })

  const text = message.content[0].type === 'text' ? message.content[0].text : '[]'
  try {
    return JSON.parse(text) as GeneratedOption[]
  } catch {
    return []
  }
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    const stockData = await Promise.all(
      OPTIONS_TICKERS.map(async (symbol) => {
        const q = await fetchQuote(symbol)
        return {
          symbol,
          price: q?.c ?? 0,
          changePct: q?.dp ?? 0,
          high52w: q?.h ?? 0,
          low52w: q?.l ?? 0,
        }
      })
    )

    const withData = stockData.filter((s) => s.price > 0)
    if (withData.length === 0) return NextResponse.json({ ok: true, count: 0 })

    const signals = await generateOptionsSignals(withData)
    if (signals.length === 0) return NextResponse.json({ ok: true, count: 0 })

    await prisma.$transaction([
      prisma.optionsSignal.updateMany({ where: { autoGenerated: true }, data: { isActive: false } }),
      ...signals.map((s) =>
        prisma.optionsSignal.create({
          data: {
            ticker: s.ticker,
            companyName: s.companyName,
            contractType: s.contractType,
            strikePrice: s.strikePrice,
            expirationDate: s.expirationDate,
            premiumEstimate: s.premiumEstimate,
            confidence: s.confidence,
            reasoning: s.reasoning,
            summary: s.summary,
            riskLevel: s.riskLevel,
            isActive: true,
            autoGenerated: true,
          },
        })
      ),
    ])

    return NextResponse.json({ ok: true, count: signals.length })
  } catch (err) {
    console.error('[cron/options]', err)
    return NextResponse.json({ error: 'Internal error' }, { status: 500 })
  }
}
