import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

// READ-ONLY diagnostic for a one-time analysis report. No writes anywhere
// in this file. To be deleted after the report is generated.
export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const cutoff30d = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)

  const [
    signals30d,
    allClosedSignals,
    optionsSignalsCount,
    optionsSample,
  ] = await Promise.all([
    prisma.signal.findMany({
      where: { autoGenerated: true, createdAt: { gte: cutoff30d } },
      select: {
        id: true, ticker: true, signalType: true, signalCategory: true,
        timeframeCategory: true, confidence: true, createdAt: true,
      },
    }),
    prisma.signal.findMany({
      where: { outcome: { in: ['HIT_TARGET', 'HIT_STOP', 'EXPIRED'] } },
      select: {
        id: true, ticker: true, signalType: true, signalCategory: true,
        timeframeCategory: true, confidence: true, createdAt: true,
        outcome: true, outcomeCheckedAt: true, outcomePrice: true,
        entryZoneLow: true, entryZoneHigh: true, targetPrice: true, stopLoss: true,
        isMomentumSpike: true,
      },
    }),
    prisma.optionsSignal.count(),
    prisma.optionsSignal.findMany({ take: 3 }),
  ])

  // ── Composition (last 30 days) ──
  const byTimeframe: Record<string, number> = {}
  const byType: Record<string, number> = {}
  const byBand: Record<string, number> = {}
  const tickerCounts: Record<string, number> = {}
  const byDay: Record<string, number> = {}
  for (const s of signals30d) {
    const tf = s.timeframeCategory ?? 'null'
    byTimeframe[tf] = (byTimeframe[tf] ?? 0) + 1
    byType[s.signalType] = (byType[s.signalType] ?? 0) + 1
    byBand[s.signalCategory] = (byBand[s.signalCategory] ?? 0) + 1
    tickerCounts[s.ticker] = (tickerCounts[s.ticker] ?? 0) + 1
    const day = s.createdAt.toISOString().slice(0, 10)
    byDay[day] = (byDay[day] ?? 0) + 1
  }
  const dayCounts = Object.values(byDay)
  const avgPerDay = dayCounts.length > 0 ? dayCounts.reduce((a, b) => a + b, 0) / dayCounts.length : 0
  const variance = dayCounts.length > 0
    ? dayCounts.reduce((sum, c) => sum + (c - avgPerDay) ** 2, 0) / dayCounts.length
    : 0
  const distinctTickers = Object.keys(tickerCounts).length
  const repeatTickers = Object.values(tickerCounts).filter((c) => c > 1).length
  const maxRepeats = Math.max(0, ...Object.values(tickerCounts))
  const topRepeats = Object.entries(tickerCounts).sort((a, b) => b[1] - a[1]).slice(0, 10)

  // ── Outcome performance by timeframeCategory ──
  function pctMove(s: (typeof allClosedSignals)[number]): number | null {
    if (s.outcomePrice == null) return null
    const mid = (s.entryZoneLow + s.entryZoneHigh) / 2
    if (mid <= 0) return null
    const raw = ((s.outcomePrice - mid) / mid) * 100
    // SHORT/SELL signals profit on a price decline — invert so "gain" always means "the trade made money"
    return (s.signalType === 'SHORT' || s.signalType === 'SELL') ? -raw : raw
  }

  const categories = ['intraday', 'days_1_3', 'swing', 'long_term', 'momentum', 'null'] as const
  const outcomeByCategory: Record<string, unknown> = {}
  for (const cat of categories) {
    const rows = allClosedSignals.filter((s) => (s.timeframeCategory ?? 'null') === cat)
    const hitTarget = rows.filter((r) => r.outcome === 'HIT_TARGET')
    const hitStop = rows.filter((r) => r.outcome === 'HIT_STOP')
    const expired = rows.filter((r) => r.outcome === 'EXPIRED')
    const total = rows.length
    const winRate = total > 0 ? hitTarget.length / total : null

    const timesToOutcome = rows
      .filter((r) => r.outcomeCheckedAt)
      .map((r) => (r.outcomeCheckedAt!.getTime() - r.createdAt.getTime()) / (1000 * 60 * 60 * 24))
    const avgDaysToOutcome = timesToOutcome.length > 0
      ? timesToOutcome.reduce((a, b) => a + b, 0) / timesToOutcome.length
      : null

    const winMoves = hitTarget.map(pctMove).filter((v): v is number => v !== null)
    const lossMoves = hitStop.map(pctMove).filter((v): v is number => v !== null)
    const avgWinPct = winMoves.length > 0 ? winMoves.reduce((a, b) => a + b, 0) / winMoves.length : null
    const avgLossPct = lossMoves.length > 0 ? lossMoves.reduce((a, b) => a + b, 0) / lossMoves.length : null

    const lossRate = total > 0 ? hitStop.length / total : null
    const expectancy = (winRate !== null && avgWinPct !== null && lossRate !== null && avgLossPct !== null)
      ? (winRate * avgWinPct) - (lossRate * Math.abs(avgLossPct))
      : null

    outcomeByCategory[cat] = {
      sampleSize: total,
      reliableSample: total >= 25,
      hitTarget: hitTarget.length,
      hitStop: hitStop.length,
      expired: expired.length,
      winRate: winRate !== null ? Math.round(winRate * 1000) / 10 : null,
      avgDaysToOutcome: avgDaysToOutcome !== null ? Math.round(avgDaysToOutcome * 100) / 100 : null,
      avgWinPct: avgWinPct !== null ? Math.round(avgWinPct * 100) / 100 : null,
      avgLossPct: avgLossPct !== null ? Math.round(avgLossPct * 100) / 100 : null,
      expectancyPct: expectancy !== null ? Math.round(expectancy * 100) / 100 : null,
    }
  }

  // Also isolate real momentum-scanner signals (isMomentumSpike) vs any legacy 'momentum' timeframeCategory rows
  const realMomentum = allClosedSignals.filter((s) => s.isMomentumSpike)
  const realMomentumHit = realMomentum.filter((r) => r.outcome === 'HIT_TARGET').length
  const realMomentumStop = realMomentum.filter((r) => r.outcome === 'HIT_STOP').length
  const realMomentumExpired = realMomentum.filter((r) => r.outcome === 'EXPIRED').length

  // ── Confidence bucket win rates ──
  const buckets = [
    { label: '<50', min: 0, max: 50 },
    { label: '50-60', min: 50, max: 60 },
    { label: '60-70', min: 60, max: 70 },
    { label: '70-80', min: 70, max: 80 },
    { label: '80+', min: 80, max: 1000 },
  ]
  const confidenceBuckets = buckets.map((b) => {
    const rows = allClosedSignals.filter((s) => s.confidence >= b.min && s.confidence < b.max)
    const hit = rows.filter((r) => r.outcome === 'HIT_TARGET').length
    const total = rows.length
    return {
      bucket: b.label,
      sampleSize: total,
      winRate: total > 0 ? Math.round((hit / total) * 1000) / 10 : null,
    }
  })

  // ── Pending / still-open counts by category (for completeness) ──
  const pendingByCategory: Record<string, number> = {}
  const allSignalsForPending = await prisma.signal.findMany({
    where: { outcome: null },
    select: { timeframeCategory: true },
  })
  for (const s of allSignalsForPending) {
    const tf = s.timeframeCategory ?? 'null'
    pendingByCategory[tf] = (pendingByCategory[tf] ?? 0) + 1
  }

  return NextResponse.json({
    composition30d: {
      totalSignals: signals30d.length,
      byTimeframe,
      byType,
      byBand,
      avgPerDay: Math.round(avgPerDay * 100) / 100,
      variance: Math.round(variance * 100) / 100,
      stdDev: Math.round(Math.sqrt(variance) * 100) / 100,
      distinctTickers,
      repeatTickers,
      maxRepeatsForOneTicker: maxRepeats,
      topRepeatedTickers: topRepeats,
      activeDaysInWindow: dayCounts.length,
    },
    outcomesByCategory: outcomeByCategory,
    pendingByCategory,
    realMomentumSpike: {
      totalClosed: realMomentum.length,
      hitTarget: realMomentumHit,
      hitStop: realMomentumStop,
      expired: realMomentumExpired,
      winRate: realMomentum.length > 0 ? Math.round((realMomentumHit / realMomentum.length) * 1000) / 10 : null,
    },
    confidenceBuckets,
    options: {
      totalCount: optionsSignalsCount,
      hasOutcomeTrackingFields: 'outcome' in (optionsSample[0] ?? {}),
      sampleRow: optionsSample[0] ?? null,
    },
    totalClosedAllTime: allClosedSignals.length,
  })
}
