import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getAnthropicClient } from '@/lib/anthropic'
import { getQuotes } from '@/lib/schwab'

export const maxDuration = 60

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

const INTRADAY_WATCHLIST = [
  'NVDA', 'TSLA', 'AMD', 'META', 'AMZN', 'GOOGL', 'MSFT', 'AAPL',
  'PLTR', 'COIN', 'MARA', 'RIOT', 'RXRX', 'HIMS', 'RKLB', 'SOUN',
  'SOFI', 'AFRM', 'HOOD', 'UBER', 'SQ', 'SNAP',
  'BBAI', 'IONQ', 'ASTS', 'LUNR', 'ACHR', 'SMCI', 'CRWD', 'DDOG',
]

type IntradaySignal = {
  ticker: string
  companyName: string
  signalType: 'BUY' | 'WATCH' | 'SHORT'
  entryZoneLow: number
  entryZoneHigh: number
  targetPrice: number
  stopLoss: number
  confidence: number
  thesis: string
  aiSummary: string
  sector: string
  bestEntryTime: string
  expectedMove: string
  catalyst: string
}

async function generateIntradaySignals(
  stocks: { symbol: string; price: number; changePct: number; open: number; high: number; low: number }[]
): Promise<IntradaySignal[]> {
  if (stocks.length === 0) return []
  const client = getAnthropicClient()

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 4096,
    messages: [
      {
        role: 'user',
        content: `You are an expert day trader analyzing stocks for intraday opportunities at market open (9:30am EST, today: ${new Date().toISOString().split('T')[0]}).

Generate 3-8 intraday trading signals for stocks showing strong momentum, technical breakouts, or catalyst-driven moves. MINIMUM confidence is 75 — only include high-conviction setups. Reply with a JSON array only, no markdown.

Each signal must have exactly these keys:
- ticker (string)
- companyName (string, full company name)
- signalType ("BUY", "WATCH", or "SHORT")
- entryZoneLow (number)
- entryZoneHigh (number)
- targetPrice (number)
- stopLoss (number)
- confidence (float 75–100, one decimal place)
- thesis (string, 1-2 sentences)
- aiSummary (string, 1 sentence)
- sector (string: "Technology", "Healthcare", "Finance", "Energy", "Consumer", "Industrials", "Defense", "Clean Energy", "Cryptocurrency", "Biotech", "Real Estate")
- bestEntryTime (string — exactly one of: "Market Open", "First 30 Minutes", "After 10am EST")
- expectedMove (string, e.g. "2–4% upside", "3–5% move expected")
- catalyst (string, 1 sentence describing what is driving the intraday move)

Stock data (price, % change today, open, high, low):
${JSON.stringify(stocks, null, 2)}`,
      },
    ],
  })

  const text = message.content[0].type === 'text' ? message.content[0].text : '[]'
  const cleaned = text.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/i, '').trim()
  try {
    return JSON.parse(cleaned) as IntradaySignal[]
  } catch {
    const match = cleaned.match(/\[[\s\S]*\]/)
    if (match) {
      try { return JSON.parse(match[0]) as IntradaySignal[] } catch { return [] }
    }
    return []
  }
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    // Skip if we already generated intraday signals today
    const todayStart = new Date()
    todayStart.setHours(0, 0, 0, 0)
    const existingCount = await prisma.signal.count({
      where: { timeHorizon: 'Intraday', autoGenerated: true, createdAt: { gte: todayStart } },
    })
    if (existingCount > 0) {
      return NextResponse.json({ ok: true, count: 0, skipped: true })
    }

    const quotes = await getQuotes(INTRADAY_WATCHLIST)
    const withData = INTRADAY_WATCHLIST
      .map((symbol) => {
        const q = quotes.get(symbol)
        return q && q.lastPrice > 0
          ? { symbol, price: q.lastPrice, changePct: q.netPercentChange, open: q.openPrice, high: q.highPrice, low: q.lowPrice }
          : null
      })
      .filter(Boolean) as { symbol: string; price: number; changePct: number; open: number; high: number; low: number }[]

    if (withData.length === 0) {
      return NextResponse.json({ ok: true, count: 0 })
    }

    const signals = await generateIntradaySignals(withData)
    const valid = signals.filter(s =>
      s.ticker &&
      s.entryZoneLow > 0 &&
      s.entryZoneHigh > 0 &&
      s.targetPrice > 0 &&
      s.stopLoss > 0 &&
      s.confidence >= 75
    )

    if (valid.length === 0) {
      return NextResponse.json({ ok: true, count: 0 })
    }

    const LARGE_CAP = new Set([
      'NVDA', 'TSLA', 'AMD', 'META', 'AMZN', 'GOOGL', 'MSFT', 'AAPL',
      'PLTR', 'COIN', 'UBER', 'CRWD', 'DDOG', 'SMCI',
    ])

    await prisma.$transaction(
      valid.map(s =>
        prisma.signal.create({
          data: {
            ticker: s.ticker,
            companyName: s.companyName,
            signalType: s.signalType,
            entryZoneLow: s.entryZoneLow,
            entryZoneHigh: s.entryZoneHigh,
            targetPrice: s.targetPrice,
            stopLoss: s.stopLoss,
            confidence: s.confidence,
            timeHorizon: 'Intraday',
            timeframeCategory: 'intraday',
            thesis: s.thesis,
            aiSummary: s.aiSummary,
            sector: s.sector,
            signalCategory: LARGE_CAP.has(s.ticker) ? 'large_cap' : 'small_cap',
            marketCap: LARGE_CAP.has(s.ticker) ? 15 : 2,
            bestEntryTime: s.bestEntryTime,
            expectedMove: s.expectedMove,
            catalyst: s.catalyst,
            isActive: true,
            autoGenerated: true,
          },
        })
      )
    )

    return NextResponse.json({ ok: true, count: valid.length })
  } catch (err) {
    console.error('[cron/intraday-signals]', err)
    return NextResponse.json({ error: 'Internal error' }, { status: 500 })
  }
}
