/**
 * Admin signal CRUD — POST (create), PATCH (edit), DELETE.
 *
 * isManual is forced true on every write here. A hand-created signal is
 * obviously manual; a hand-EDITED algorithm signal is too, because its
 * trade parameters no longer reflect what the algorithm produced. Once set
 * it is never cleared. See lib/publicStats.ts for what that flag excludes.
 *
 * Security: requireAdmin() on every request (server-side, per-request).
 */
import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireAdmin, logAdminAction } from '@/lib/adminAuth'
import { checkRateLimit, tooManyRequests, ADMIN_LIMIT, ADMIN_WINDOW_MS } from '@/lib/rate-limit'

export const dynamic = 'force-dynamic'

type SignalPayload = {
  ticker?: unknown
  companyName?: unknown
  signalType?: unknown
  entryZoneLow?: unknown
  entryZoneHigh?: unknown
  targetPrice?: unknown
  stopLoss?: unknown
  confidence?: unknown
  timeHorizon?: unknown
  timeframeCategory?: unknown
  thesis?: unknown
  aiSummary?: unknown
  sector?: unknown
  signalCategory?: unknown
}

const VALID_TYPES = ['BUY', 'WATCH', 'SHORT', 'SELL']
const VALID_TIMEFRAMES = ['intraday', 'days_1_3', 'swing', 'long_term', 'momentum']

function num(v: unknown): number | null {
  const n = typeof v === 'string' ? parseFloat(v) : typeof v === 'number' ? v : NaN
  return Number.isFinite(n) ? n : null
}

function str(v: unknown): string {
  return typeof v === 'string' ? v.trim() : ''
}

/** Full validation for creates. Mirrors the invariants the generation crons enforce. */
function validateCreate(body: SignalPayload): { ok: true; data: Record<string, unknown> } | { ok: false; error: string } {
  const ticker = str(body.ticker).toUpperCase()
  if (!ticker) return { ok: false, error: 'Ticker is required' }

  const signalType = str(body.signalType).toUpperCase()
  if (!VALID_TYPES.includes(signalType)) return { ok: false, error: `Signal type must be one of ${VALID_TYPES.join(', ')}` }

  const entryZoneLow = num(body.entryZoneLow)
  const entryZoneHigh = num(body.entryZoneHigh)
  const targetPrice = num(body.targetPrice)
  const stopLoss = num(body.stopLoss)
  if (entryZoneLow === null || entryZoneLow <= 0) return { ok: false, error: 'Entry zone low must be a positive number' }
  if (entryZoneHigh === null || entryZoneHigh <= 0) return { ok: false, error: 'Entry zone high must be a positive number' }
  if (entryZoneHigh < entryZoneLow) return { ok: false, error: 'Entry zone high must be >= entry zone low' }
  if (targetPrice === null || targetPrice <= 0) return { ok: false, error: 'Target price must be a positive number' }
  if (stopLoss === null || stopLoss <= 0) return { ok: false, error: 'Stop loss must be a positive number' }

  const confidence = num(body.confidence)
  if (confidence === null || confidence < 0 || confidence > 100) {
    return { ok: false, error: 'Confidence must be a number between 0 and 100' }
  }

  const timeframeCategory = str(body.timeframeCategory)
  if (!VALID_TIMEFRAMES.includes(timeframeCategory)) {
    return { ok: false, error: `Timeframe must be one of ${VALID_TIMEFRAMES.join(', ')}` }
  }

  const thesis = str(body.thesis)
  if (!thesis) return { ok: false, error: 'Thesis is required' }

  const signalCategory = str(body.signalCategory) || 'large_cap'

  return {
    ok: true,
    data: {
      ticker,
      companyName: str(body.companyName) || ticker,
      signalType,
      entryZoneLow,
      entryZoneHigh,
      targetPrice,
      stopLoss,
      confidence,
      timeHorizon: str(body.timeHorizon) || timeframeCategory,
      timeframeCategory,
      thesis,
      aiSummary: str(body.aiSummary) || thesis.slice(0, 160),
      sector: str(body.sector) || 'Unknown',
      signalCategory,
      marketCap: signalCategory === 'large_cap' ? 15 : 2,
      isActive: true,
      autoGenerated: false,
      isManual: true,
    },
  }
}

export async function POST(req: Request) {
  const adminId = await requireAdmin()
  if (!adminId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const rl = checkRateLimit(`admin-signal-create:${adminId}`, ADMIN_LIMIT, ADMIN_WINDOW_MS)
  if (!rl.success) return tooManyRequests(rl.retryAfter!)

  let body: SignalPayload
  try { body = await req.json() } catch { return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 }) }

  const validated = validateCreate(body)
  if (!validated.ok) return NextResponse.json({ error: validated.error }, { status: 400 })

  try {
    const signal = await prisma.signal.create({ data: validated.data as never })
    await logAdminAction({
      adminId, action: 'signal.create', target: signal.ticker,
      detail: `${signal.signalType} ${signal.ticker} @ ${signal.entryZoneLow}-${signal.entryZoneHigh} (manual)`,
    })
    return NextResponse.json({ ok: true, id: signal.id })
  } catch (e) {
    console.error('[admin/signal] create failed', e)
    return NextResponse.json({ error: 'Failed to create signal' }, { status: 500 })
  }
}

export async function PATCH(req: Request) {
  const adminId = await requireAdmin()
  if (!adminId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const rl = checkRateLimit(`admin-signal-edit:${adminId}`, ADMIN_LIMIT, ADMIN_WINDOW_MS)
  if (!rl.success) return tooManyRequests(rl.retryAfter!)

  let body: SignalPayload & { id?: unknown; isActive?: unknown }
  try { body = await req.json() } catch { return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 }) }

  const id = str(body.id)
  if (!id) return NextResponse.json({ error: 'id is required' }, { status: 400 })

  // Build a partial update from only the fields actually supplied.
  const data: Record<string, unknown> = {}
  const numericFields = ['entryZoneLow', 'entryZoneHigh', 'targetPrice', 'stopLoss', 'confidence'] as const
  for (const f of numericFields) {
    if (body[f] !== undefined) {
      const v = num(body[f])
      if (v === null || v < 0) return NextResponse.json({ error: `${f} must be a non-negative number` }, { status: 400 })
      if (f === 'confidence' && v > 100) return NextResponse.json({ error: 'Confidence must be 0-100' }, { status: 400 })
      data[f] = v
    }
  }
  if (body.signalType !== undefined) {
    const t = str(body.signalType).toUpperCase()
    if (!VALID_TYPES.includes(t)) return NextResponse.json({ error: 'Invalid signal type' }, { status: 400 })
    data.signalType = t
  }
  if (body.timeframeCategory !== undefined) {
    const tf = str(body.timeframeCategory)
    if (!VALID_TIMEFRAMES.includes(tf)) return NextResponse.json({ error: 'Invalid timeframe' }, { status: 400 })
    data.timeframeCategory = tf
  }
  if (body.thesis !== undefined) data.thesis = str(body.thesis)
  if (body.isActive !== undefined) data.isActive = Boolean(body.isActive)

  if (Object.keys(data).length === 0) {
    return NextResponse.json({ error: 'No editable fields supplied' }, { status: 400 })
  }

  // A hand-edit means the stored parameters are no longer purely algorithm
  // output — flag it so it drops out of the published track record.
  const isToggleOnly = Object.keys(data).length === 1 && 'isActive' in data
  if (!isToggleOnly) data.isManual = true

  try {
    const signal = await prisma.signal.update({ where: { id }, data })
    await logAdminAction({
      adminId,
      action: isToggleOnly ? 'signal.toggle' : 'signal.edit',
      target: signal.ticker,
      detail: isToggleOnly
        ? `isActive -> ${signal.isActive}`
        : `edited ${Object.keys(data).filter((k) => k !== 'isManual').join(', ')}; flagged manual`,
    })
    return NextResponse.json({ ok: true })
  } catch (e) {
    console.error('[admin/signal] update failed', e)
    return NextResponse.json({ error: 'Failed to update signal' }, { status: 500 })
  }
}

export async function DELETE(req: Request) {
  const adminId = await requireAdmin()
  if (!adminId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const rl = checkRateLimit(`admin-signal-delete:${adminId}`, ADMIN_LIMIT, ADMIN_WINDOW_MS)
  if (!rl.success) return tooManyRequests(rl.retryAfter!)

  const id = new URL(req.url).searchParams.get('id')
  if (!id) return NextResponse.json({ error: 'id is required' }, { status: 400 })

  try {
    const signal = await prisma.signal.delete({ where: { id } })
    await logAdminAction({ adminId, action: 'signal.delete', target: signal.ticker, detail: `deleted ${signal.signalType} ${signal.ticker}` })
    return NextResponse.json({ ok: true })
  } catch (e) {
    console.error('[admin/signal] delete failed', e)
    return NextResponse.json({ error: 'Failed to delete signal' }, { status: 500 })
  }
}
