import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../app/generated/prisma/client/index.js'
import { readFileSync } from 'fs'
import { join } from 'path'

// Load .env.local
const envPath = join(process.cwd(), '.env.local')
const lines = readFileSync(envPath, 'utf8').split('\n')
for (const line of lines) {
  const trimmed = line.trim()
  if (!trimmed || trimmed.startsWith('#')) continue
  const idx = trimmed.indexOf('=')
  if (idx === -1) continue
  const key = trimmed.slice(0, idx).trim()
  const val = trimmed.slice(idx + 1).trim()
  if (!(key in process.env)) process.env[key] = val
}

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

const signals = await prisma.signal.findMany({ where: { isActive: true }, orderBy: { createdAt: 'desc' } })
console.log(`Total active signals: ${signals.length}`)
for (const s of signals) {
  const nullFields = Object.entries(s).filter(([, v]) => v === null || v === undefined).map(([k]) => k)
  console.log(JSON.stringify({
    ticker: s.ticker,
    type: s.signalType,
    confidence: s.confidence,
    nullFields,
    entryLow: s.entryZoneLow,
    entryHigh: s.entryZoneHigh,
    target: s.targetPrice,
    stop: s.stopLoss,
    autoGen: s.autoGenerated,
    summaryLen: (s.aiSummary || '').length,
    thesisLen: (s.thesis || '').length,
  }))
}

await prisma.$disconnect()
