// TEMPORARY DIAGNOSTIC — DELETE AFTER USE
//
// GET /api/cron/signal-diagnostics
// (moved here after every /api/admin/* route — including old, previously
// working ones like /api/admin/health-check — 404'd consistently in
// production, while every /api/cron/* route worked 100% of the time all
// session. Root cause was ultimately a Vercel domain conflict: www.holoture.com
// was assigned to two projects at once (holoture-app + a stale, abandoned
// holoture-website), which was fixed separately, but this route still 404'd
// under /api/admin/ afterward — moved here rather than sink more time into it,
// since this is a throwaway diagnostic, not a permanent route.)
// Read-only report on signal generation reality: category breakdown,
// classification-function reality check, ticker repetition, outcome data,
// and dedup impact. No writes, no mutations, no deletes.
//
// Auth: Bearer CRON_SECRET only, matching every other /api/cron/* route.

import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'
export const maxDuration = 60

function isAuthorized(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  return !!secret && req.headers.get('authorization') === `Bearer ${secret}`
}

// ── Exact copies of the client's classification functions
//    (SignalBoardClient.tsx:51-71) — used only to check what they'd report
//    against real stored timeHorizon strings. Not used to write anything. ──
function isLongTerm(h: string): boolean {
  const lower = h.toLowerCase()
  if (lower.includes('year')) return true
  if (lower.includes('month')) {
    const m = lower.match(/(\d+)/)
    return m != null && parseInt(m[1]) >= 3
  }
  return false
}
function isSwingTrade(h: string): boolean {
  return h.toLowerCase().includes('week')
}
function isMomentum(signalType: string, confidence: number): boolean {
  return signalType === 'BUY' && confidence >= 75
}
function isIntraday(h: string): boolean {
  return /intraday|hour/i.test(h)
}
function is1to3Days(h: string): boolean {
  return /1[-–]3\s*day|1-3\s*day/i.test(h)
}

const LARGE_CAP_WATCHLIST = [
  'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META', 'AMZN', 'TSLA', 'AVGO', 'AMD', 'QCOM',
  'INTC', 'TXN', 'MU', 'AMAT', 'ADBE', 'CRM', 'ORCL', 'SNOW', 'CRWD', 'DDOG',
  'JPM', 'BAC', 'GS', 'V', 'MA', 'C', 'WFC', 'MS', 'BLK', 'SCHW', 'AXP',
  'JNJ', 'UNH', 'LLY', 'PFE', 'ABT', 'TMO', 'ISRG', 'AMGN', 'GILD',
  'XOM', 'CVX', 'COP', 'EOG', 'SLB',
  'WMT', 'COST', 'MCD', 'SBUX', 'TGT', 'KO', 'PEP', 'NKE',
  'CAT', 'HON', 'RTX', 'LMT', 'GE',
  'NFLX', 'DIS', 'CMCSA',
  'PLTR', 'COIN', 'AXON', 'UBER', 'SOFI', 'AFRM',
]

const SMALL_CAP_WATCHLIST = [
  'RXRX', 'BEAM', 'NTLA', 'PACB', 'ARWR', 'EDIT',
  'HIMS', 'ACCD', 'PRVA', 'GDRX',
  'RKLB', 'ACHR', 'JOBY', 'LUNR', 'ASTS',
  'MARA', 'RIOT', 'CLSK', 'CIFR',
  'BBAI', 'SOUN', 'KTOS',
  'LCID', 'NKLA', 'GOEV',
  'NOVA', 'ARRY', 'STEM', 'SHLS',
  'SEMR', 'BRZE', 'WEAV', 'IONQ',
  'NARI', 'INSP', 'ATEC',
  'OPEN', 'UWMC', 'COOP',
  'BROS', 'CAVA', 'SFM', 'SKIN', 'PRTS',
  'SWBI', 'RGR', 'POWL',
  'CIVI', 'MGY', 'VTLE', 'CHRD',
  'LYFT', 'U', 'TTWO',
]

function dateKeyET(d: Date): string {
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York' }).format(d)
}

export async function GET(req: Request) {
  if (!isAuthorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const cutoff14d = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)

    // Pull everything needed once; all sections below are read-only derivations.
    const last14dSignals = await prisma.signal.findMany({
      where: { createdAt: { gte: cutoff14d } },
      select: {
        ticker: true, signalCategory: true, signalType: true, timeHorizon: true,
        confidence: true, createdAt: true, autoGenerated: true,
      },
    })

    // ── 1. Per-day breakdown ──────────────────────────────────────────────
    type DayBucket = {
      total: number
      byCategory: Record<string, number>
      byType: Record<string, number>
      byTimeHorizon: Record<string, number>
    }
    const perDay = new Map<string, DayBucket>()
    for (const s of last14dSignals) {
      const key = dateKeyET(s.createdAt)
      if (!perDay.has(key)) perDay.set(key, { total: 0, byCategory: {}, byType: {}, byTimeHorizon: {} })
      const bucket = perDay.get(key)!
      bucket.total++
      bucket.byCategory[s.signalCategory] = (bucket.byCategory[s.signalCategory] ?? 0) + 1
      bucket.byType[s.signalType] = (bucket.byType[s.signalType] ?? 0) + 1
      bucket.byTimeHorizon[s.timeHorizon] = (bucket.byTimeHorizon[s.timeHorizon] ?? 0) + 1
    }
    const perDayReport = [...perDay.entries()]
      .sort((a, b) => b[0].localeCompare(a[0]))
      .map(([date, bucket]) => ({ date, ...bucket }))

    // ── 2. Classification reality check ──────────────────────────────────
    let matchIntraday = 0, matchDays13 = 0, matchSwing = 0, matchLongTerm = 0, matchMomentum = 0, matchNone = 0
    const orphanedTimeHorizons = new Set<string>()
    for (const s of last14dSignals) {
      const h = s.timeHorizon
      const hitIntraday = isIntraday(h)
      const hitDays13 = is1to3Days(h)
      const hitSwing = isSwingTrade(h)
      const hitLongTerm = isLongTerm(h)
      const hitMomentum = isMomentum(s.signalType, s.confidence)
      if (hitIntraday) matchIntraday++
      if (hitDays13) matchDays13++
      if (hitSwing) matchSwing++
      if (hitLongTerm) matchLongTerm++
      if (hitMomentum) matchMomentum++
      if (!hitIntraday && !hitDays13 && !hitSwing && !hitLongTerm && !hitMomentum) {
        matchNone++
        orphanedTimeHorizons.add(h)
      }
    }

    // ── 3. Ticker repetition ─────────────────────────────────────────────
    const allSignalsTickersOnly = await prisma.signal.findMany({
      select: { ticker: true, createdAt: true },
      orderBy: { createdAt: 'desc' },
    })
    const tickerCounts = new Map<string, { count: number; mostRecent: Date }>()
    for (const s of allSignalsTickersOnly) {
      const existing = tickerCounts.get(s.ticker)
      if (existing) {
        existing.count++
        if (s.createdAt > existing.mostRecent) existing.mostRecent = s.createdAt
      } else {
        tickerCounts.set(s.ticker, { count: 1, mostRecent: s.createdAt })
      }
    }
    const distinctTickersEver = tickerCounts.size
    const top25 = [...tickerCounts.entries()]
      .sort((a, b) => b[1].count - a[1].count)
      .slice(0, 25)
      .map(([ticker, v]) => ({ ticker, appearances: v.count, mostRecent: v.mostRecent.toISOString() }))

    const distinctTickersLast14d = new Set(last14dSignals.map((s) => s.ticker)).size

    const everAppeared = new Set(tickerCounts.keys())
    const neverAppearedLargeCap = LARGE_CAP_WATCHLIST.filter((t) => !everAppeared.has(t))
    const neverAppearedSmallCap = SMALL_CAP_WATCHLIST.filter((t) => !everAppeared.has(t))

    // ── 4. Outcome data ──────────────────────────────────────────────────
    const [hitTarget, hitStop, expired, pending] = await Promise.all([
      prisma.signal.count({ where: { outcome: 'HIT_TARGET' } }),
      prisma.signal.count({ where: { outcome: 'HIT_STOP' } }),
      prisma.signal.count({ where: { outcome: 'EXPIRED' } }),
      prisma.signal.count({ where: { outcome: null } }),
    ])
    const byCategory = await prisma.signal.groupBy({
      by: ['signalCategory', 'outcome'],
      _count: { _all: true },
    })
    const outcomeByCategory: Record<string, Record<string, number>> = {}
    for (const row of byCategory) {
      const cat = row.signalCategory
      const out = row.outcome ?? 'PENDING'
      if (!outcomeByCategory[cat]) outcomeByCategory[cat] = {}
      outcomeByCategory[cat][out] = row._count._all
    }
    const closedDateRange = await prisma.signal.aggregate({
      where: { outcome: { in: ['HIT_TARGET', 'HIT_STOP', 'EXPIRED'] } },
      _min: { outcomeCheckedAt: true },
      _max: { outcomeCheckedAt: true },
    })

    // ── 5. Dedup impact ──────────────────────────────────────────────────
    // For each of the last 14 generation days, count how many combined-universe
    // tickers already had an active-at-that-time signal created in the prior
    // 24h — i.e. how many were excluded from that day's candidate pool by the
    // current dedup logic (signals/route.ts:641-648).
    const combinedUniverse = new Set([...LARGE_CAP_WATCHLIST, ...SMALL_CAP_WATCHLIST])
    const allForDedup = await prisma.signal.findMany({
      where: { autoGenerated: true },
      select: { ticker: true, createdAt: true },
      orderBy: { createdAt: 'asc' },
    })
    const dedupImpact: { date: string; excludedCount: number; effectivePoolSize: number }[] = []
    const daySet = new Set(perDayReport.map((d) => d.date))
    for (const date of daySet) {
      // "As of" this generation day's 06:30 ET run — approximate with day start.
      const dayStart = new Date(`${date}T00:00:00-05:00`)
      const cutoff = new Date(dayStart.getTime() - 0) // exclusion is relative to run time
      const priorWindowStart = new Date(cutoff.getTime() - 24 * 60 * 60 * 1000)
      const excludedTickers = new Set<string>()
      for (const s of allForDedup) {
        if (s.createdAt >= priorWindowStart && s.createdAt < cutoff && combinedUniverse.has(s.ticker)) {
          excludedTickers.add(s.ticker)
        }
      }
      dedupImpact.push({
        date,
        excludedCount: excludedTickers.size,
        effectivePoolSize: combinedUniverse.size - excludedTickers.size,
      })
    }
    dedupImpact.sort((a, b) => b.date.localeCompare(a.date))

    return NextResponse.json({
      section1_perDay: perDayReport,
      section2_classificationRealityCheck: {
        totalSignalsLast14d: last14dSignals.length,
        matches: {
          intraday: matchIntraday,
          days_1_3: matchDays13,
          swing: matchSwing,
          longTerm: matchLongTerm,
          momentum: matchMomentum,
          matchesNone: matchNone,
        },
        orphanedTimeHorizonStrings: [...orphanedTimeHorizons],
      },
      section3_tickerRepetition: {
        distinctTickersEver,
        top25MostRepeated: top25,
        distinctTickersLast14d,
        combinedUniverseSize: LARGE_CAP_WATCHLIST.length + SMALL_CAP_WATCHLIST.length,
        largeCapWatchlist: { size: LARGE_CAP_WATCHLIST.length, neverAppeared: neverAppearedLargeCap },
        smallCapWatchlist: { size: SMALL_CAP_WATCHLIST.length, neverAppeared: neverAppearedSmallCap },
      },
      section4_outcomes: {
        allTime: { hitTarget, hitStop, expired, pending },
        byCategory: outcomeByCategory,
        closedDateRange: {
          earliest: closedDateRange._min.outcomeCheckedAt,
          latest: closedDateRange._max.outcomeCheckedAt,
        },
      },
      section5_dedupImpact: dedupImpact,
    })
  } catch (err) {
    return NextResponse.json({ error: err instanceof Error ? err.message : String(err) }, { status: 500 })
  }
}
