/**
 * TEMPORARY DIAGNOSTIC — GET /api/cron/diag-hit-target
 *
 * Explains why some HIT_TARGET signals don't appear in the Recent Signals
 * strip window. Reports every HIT_TARGET signal in the DB and which strip
 * filter (if any) excludes it: timeframeCategory not in [swing, long_term],
 * isManual true, or timeframeCategory null (legacy/pre-migration rows the
 * strict `in` filter can't match even though outcomeCheckedAt/outcome are
 * real). Report-only. Delete after use.
 */
import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'
export const maxDuration = 60

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    const all = await prisma.signal.findMany({
      where: { outcome: 'HIT_TARGET' },
      orderBy: { outcomeCheckedAt: 'desc' },
      select: {
        id: true, ticker: true, timeframeCategory: true, timeHorizon: true,
        isManual: true, autoGenerated: true, outcomeCheckedAt: true, signalDate: true,
      },
    })

    const included = all.filter(
      (s) => (s.timeframeCategory === 'swing' || s.timeframeCategory === 'long_term') && !s.isManual,
    )
    const excludedWrongCategory = all.filter(
      (s) => s.timeframeCategory !== 'swing' && s.timeframeCategory !== 'long_term' && s.timeframeCategory !== null,
    )
    const excludedNullCategory = all.filter((s) => s.timeframeCategory === null)
    const excludedManual = all.filter(
      (s) => s.isManual && (s.timeframeCategory === 'swing' || s.timeframeCategory === 'long_term'),
    )

    // Of the "included" set (would pass the category+manual filter), which
    // ones actually make it into the last-20-resolved window vs. get pushed
    // out by more recently resolved signals (target or stop).
    const windowCutoffRank = 20
    const allResolvedIncluded = await prisma.signal.findMany({
      where: {
        timeframeCategory: { in: ['swing', 'long_term'] },
        outcome: { in: ['HIT_TARGET', 'HIT_STOP'] },
        isManual: false,
      },
      orderBy: { outcomeCheckedAt: 'desc' },
      select: { id: true, ticker: true, outcome: true, outcomeCheckedAt: true },
    })
    const inWindowIds = new Set(allResolvedIncluded.slice(0, windowCutoffRank).map((s) => s.id))
    const pushedOutOfWindow = included
      .filter((s) => !inWindowIds.has(s.id))
      .map((s) => ({ ticker: s.ticker, outcomeCheckedAt: s.outcomeCheckedAt }))

    return NextResponse.json({
      ok: true,
      totalHitTarget: all.length,
      passesStripFilter: included.length,
      excludedByCategory: excludedWrongCategory.map((s) => ({ ticker: s.ticker, timeframeCategory: s.timeframeCategory, timeHorizon: s.timeHorizon })),
      excludedByNullCategory: excludedNullCategory.map((s) => ({ ticker: s.ticker, timeHorizon: s.timeHorizon, signalDate: s.signalDate })),
      excludedByManual: excludedManual.map((s) => ({ ticker: s.ticker, autoGenerated: s.autoGenerated })),
      totalResolvedInWindowPool: allResolvedIncluded.length,
      hitTargetPushedOutOfLast20Window: pushedOutOfWindow,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error('[cron/diag-hit-target]', msg)
    return NextResponse.json({ error: 'Internal error', message: msg }, { status: 500 })
  }
}
