import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getQuotesWithFundamentals } from '@/lib/schwab'
import { screenBand, type ScreenedTicker } from '@/lib/nasdaqScreener'
import { LARGE_CAP_MIN_DOLLAR_VOLUME, SMALL_CAP_MIN_DOLLAR_VOLUME } from '@/lib/liquidityFloor'

export const dynamic = 'force-dynamic'
export const maxDuration = 120

function verifyCron(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true
  return req.headers.get('authorization') === `Bearer ${secret}`
}

// Per-sector cap sized so 11 sectors land inside the task's target pool
// sizes while keeping every sector well under the ~15-20% diversity cap:
//   large-cap:    11 x 9  = up to 99   (target 80-100)
//   small/mid:    11 x 20 = up to 220  (target 150-250)
const LARGE_PER_SECTOR_CAP = 9
const SMALL_MID_PER_SECTOR_CAP = 20

async function applyLiquidityFloor(
  candidates: ScreenedTicker[],
  minDollarVolume: number
): Promise<Array<ScreenedTicker & { avgDollarVolume: number }>> {
  const out: Array<ScreenedTicker & { avgDollarVolume: number }> = []
  // Schwab's batch quote endpoint caps at ~500 symbols per call.
  const CHUNK = 400
  for (let i = 0; i < candidates.length; i += CHUNK) {
    const chunk = candidates.slice(i, i + CHUNK)
    const quoteMap = await getQuotesWithFundamentals(chunk.map((c) => c.ticker))
    for (const c of chunk) {
      const data = quoteMap.get(c.ticker)
      if (!data) continue
      const avgVol = data.fundamental.avg10DaysVolume
      if (avgVol == null) continue // no data — exclude here (unlike the daily generator, this is a fresh admission gate, not a re-check)
      const avgDollarVolume = data.quote.lastPrice * avgVol
      if (avgDollarVolume >= minDollarVolume) {
        out.push({ ...c, avgDollarVolume })
      }
    }
  }
  return out
}

export async function GET(req: Request) {
  if (!verifyCron(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    const [largeCandidates, smallMidCandidates] = await Promise.all([
      screenBand(['mega', 'large'], LARGE_PER_SECTOR_CAP),
      screenBand(['mid', 'small'], SMALL_MID_PER_SECTOR_CAP),
    ])

    const [largeQualified, smallMidQualified] = await Promise.all([
      applyLiquidityFloor(largeCandidates, LARGE_CAP_MIN_DOLLAR_VOLUME),
      applyLiquidityFloor(smallMidCandidates, SMALL_CAP_MIN_DOLLAR_VOLUME),
    ])

    if (largeQualified.length === 0 && smallMidQualified.length === 0) {
      // Screen returned nothing usable — leave the existing TickerUniverse
      // table (and therefore the daily generator's fallback path) untouched
      // rather than wiping it out on a bad run.
      return NextResponse.json({ ok: false, error: 'Screen returned zero qualified candidates; table left unchanged' }, { status: 200 })
    }

    const now = new Date()
    const rows = [
      ...largeQualified.map((t) => ({
        ticker: t.ticker,
        marketCapBand: 'large' as const,
        sector: t.sector,
        avgDollarVolume: t.avgDollarVolume,
        lastScreenedAt: now,
      })),
      ...smallMidQualified.map((t) => ({
        ticker: t.ticker,
        marketCapBand: 'small_mid' as const,
        sector: t.sector,
        avgDollarVolume: t.avgDollarVolume,
        lastScreenedAt: now,
      })),
    ]

    // Never-appeared diagnostic (Task 4 of Universe Expansion) — standing
    // check, not one-time: of the tickers about to make up the new
    // universe, how many have zero signals in the trailing 30 days.
    const cutoff30d = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
    const recentTickers = await prisma.signal.findMany({
      where: { autoGenerated: true, createdAt: { gte: cutoff30d } },
      select: { ticker: true },
      distinct: ['ticker'],
    })
    const recentSet = new Set(recentTickers.map((s) => s.ticker))
    const neverAppeared = rows.filter((r) => !recentSet.has(r.ticker)).length

    await prisma.$transaction([
      prisma.tickerUniverse.deleteMany({}),
      prisma.tickerUniverse.createMany({ data: rows }),
    ])

    return NextResponse.json({
      ok: true,
      universeSize: rows.length,
      largeCap: largeQualified.length,
      smallMid: smallMidQualified.length,
      neverAppearedInLast30Days: neverAppeared,
      neverAppearedPct: Math.round((neverAppeared / rows.length) * 1000) / 10,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error('[cron/universe-screen]', msg)
    return NextResponse.json({ error: 'Internal error', message: msg }, { status: 500 })
  }
}
